typography_spectrum: 0.75147
color:
  brandColors:
    - '#010801'
    - '#ffffff'
    - '#38d847'
    - '#ccd1cc'
    - '#56685c'
  brandStrength: 1
  lightness: 0.1599323854316026
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.47222
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gerardo Guerra
  email: gguerra@londrafilms.com
  url: www.londrafilms.com
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 1. LONDRA Films  - home page
    id: 8d90169a-43fa-4b41-912c-90b85ff6fd33
    type: content
  - name: 2. PRODUCCIÓN
    id: 9ef77ff5-53ba-4475-8fab-8826ccd64ef3
    type: content
  - name: 3rd EQUIPOS AUDIOVISUALES
    id: 4f71a513-c295-473b-890c-813bded00a4f
    type: content
  - name: 4th DISTRIBUCIÓN
    id: 031e1ec2-04b6-4f9c-8997-4277986180cf
    type: content
  - name: 5th Facebook
    url: 'http://www.facebook.com/LONDRA.Films/'
    type: external
favicon: null
title: LONDRA Films P&D - Bolivia
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
