typography_spectrum: 0.3536571820732206
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.3437290866859257
  lightness: 0.3572493956889957
  saturation: 0.10957968328148127
  rhythmicContrast: 0.7060413483995944
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9354616794735193
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gerardo Guerra
  email: gguerra@londrafilms.com
  url: www.londrafilms.com
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: PRODUCCIÓN
    id: 5fb114a1-19d1-494b-b0d5-a41329ca03f7
    type: content
  - name: Ding Dong
    id: 969a4eb5-c275-4920-8790-2b9dcaa2fad5
    type: content
  - name: DITRIBUCIÓN
    id: 172ac70b-eb64-40a7-870c-af139e4a98a6
    type: content
favicon: null
title: LONDRA Films P&D - Bolivia
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
