typography_spectrum: 0.75147
color:
  brandColors:
    - '#010801'
    - '#ffffff'
    - '#38d847'
    - '#ccd1cc'
    - '#56685c'
  brandStrength: 1
  lightness: 0.1599323854316026
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.47222
analytics:
  google: null
  facebook: null
  twitter: null
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: LONDRA Films P&D
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
