typography_spectrum: 0.29760355525650084
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.05142619973048568
  lightness: 0.16979496064595878
  saturation: 0.2295075247529894
  rhythmicContrast: 0.06597118312492967
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7312393374741077
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gerardo Guerra
  email: gguerra@londrafilms.com
  url: www.londrafilms.com
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: 843b7d0b-95d4-495b-857a-17dcd307d135
    type: content
  - name: PRODUCCIÓN
    id: 5fb114a1-19d1-494b-b0d5-a41329ca03f7
    type: content
  - name: DISTRIBUCIÓN
    id: 172ac70b-eb64-40a7-870c-af139e4a98a6
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/LONDRA.Films/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/LONDRAfilms'
    type: external
  - name: WELCOME
    id: e16eff53-32d6-4018-ae95-dbb600600f51
    type: content
favicon: null
title: LONDRA Films P&D - Bolivia
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
