typography_spectrum: 0.5723035652190447
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.3437290866859257
  lightness: 0.3572493956889957
  saturation: 0.10957968328148127
  rhythmicContrast: 0.7060413483995944
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11616774881258607
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gerardo Guerra
  email: gguerra@londrafilms.com
  url: www.londrafilms.com
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 1. LONDRA Films  - homepage
    id: 8d90169a-43fa-4b41-912c-90b85ff6fd33
    type: content
  - name: Ding Dong test
    url: 'http://www.eldeber.com.bo/escenas/escucha-sonido-del-ganador-ding.html'
    type: external
  - name: Bolitas
    url: 'https://www.youtube.com/watch?v=12Xcjlnnb3c'
    type: external
favicon: null
title: LONDRA Films P&D - Bolivia
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
