typography_spectrum: 0.9368375088088214
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.14408086333423853
  lightness: 0.9026999222114682
  saturation: 0.6251135778147727
  rhythmicContrast: 0.9241571994498372
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4514114644844085
analytics:
  google: null
  facebook: null
  twitter: null
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LONDRA Films  - home page
    id: 8d90169a-43fa-4b41-912c-90b85ff6fd33
    type: content
  - name: PRODUCCIÓN
    id: 9ef77ff5-53ba-4475-8fab-8826ccd64ef3
    type: content
  - name: DISTRIBUCIÓN
    id: 031e1ec2-04b6-4f9c-8997-4277986180cf
    type: content
  - name: EQUIPOS AUDIOVISUALES
    id: 4f71a513-c295-473b-890c-813bded00a4f
    type: content
  - name: Facebook LONDRA Films P&D
    url: 'http://www.facebook.com/LONDRA.Films/'
    type: external
favicon: null
title: LONDRA Films P&D
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
