name: LONDRA Films P&D
favicon: null
layout_spectrum: 0.47222
typography_spectrum: 0.75147
title: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010801'
    - '#ffffff'
    - '#38d847'
    - '#ccd1cc'
    - '#56685c'
  brandStrength: 0.5
  lightness: 0.1599323854316026
  saturation: 0.5
  rhythmicContrast: 0.9796432629227638
purpose: []
