layout_spectrum: 0.4365153934340924
typography_spectrum: 0.34522787551395595
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.3437290866859257
  lightness: 0.3572493956889957
  saturation: 0.10957968328148127
  rhythmicContrast: 0.7060413483995944
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gerardo Guerra
  email: gguerra@londrafilms.com
  url: www.londrafilms.com
name: LONDRA Films P&D
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 1. LONDRA Films  - home page
    id: 8d90169a-43fa-4b41-912c-90b85ff6fd33
    type: content
  - name: 2. PRODUCCIÓN
    id: 9ef77ff5-53ba-4475-8fab-8826ccd64ef3
    type: content
  - name: 3.  DISTRIBUCIÓN
    id: 031e1ec2-04b6-4f9c-8997-4277986180cf
    type: content
  - name: 'YO, OLGA HEPNAROVA - Trailer'
    id: 287a1439-3da2-4f3a-994c-fae1cc7ec9a6
    type: content
  - name: 4. EQUIPOS AUDIOVISUALES
    id: 4f71a513-c295-473b-890c-813bded00a4f
    type: content
  - name: 5 Facebook
    url: 'http://www.facebook.com/LONDRA.Films/'
    type: external
  - name: 6 LONDRA Films P&D en Twitter
    url: 'https://twitter.com/LONDRAfilms'
    type: external
  - name: Escena
    id: 3d69e32b-60a1-4545-b014-5a7981db2613
    type: content
favicon: null
title: LONDRA Films P&D - Bolivia
description: Producción y Distribución Cinematográfica en Bolivia
purpose: []
